GET http://localhost:3000/subscribers/

###

GET http://localhost:3000/subscribers/5f7d0f7c5ec9356481da8871

###

POST http://localhost:3000/subscribers/
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/5f7d0f7c5ec9356481da8871

###

PATCH http://localhost:3000/subscribers/5f7d101d7475d0658fbaf05c
Content-Type: application/json

{
    "name": "New Name"
}
